post_install() {
  if ! getent group gitprep >/dev/null; then
    groupadd --system gitprep
  fi
  if ! getent passwd gitprep >/dev/null; then
    useradd --system -c 'gitprep daemon user' -g gitprep -d / -s /bin/bash gitprep
  fi
}

post_upgrade() {
  post_install $1
}

post_remove() {
  if getent passwd gitprep >/dev/null; then
    userdel gitprep
  fi
  if getent group gitprep >/dev/null; then
    groupdel gitprep
  fi
}
